--------------------------------------------------------
-- Archivo creado  - lunes-mayo-02-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "CUENTAS_BP"."CLIENTE" 
   (	"ID" NUMBER, 
	"CLIENTE_ID" VARCHAR2(100 BYTE), 
	"CONTRASENIA" VARCHAR2(20 BYTE), 
	"ESTADO" VARCHAR2(1 BYTE), 
	"NOMBRE" VARCHAR2(200 BYTE), 
	"GENERO" VARCHAR2(20 BYTE), 
	"EDAD" NUMBER, 
	"IDENTIFICACION" VARCHAR2(10 BYTE), 
	"DIRECCION" VARCHAR2(200 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CUENTAS_BP.CLIENTE
SET DEFINE OFF;
Insert into CUENTAS_BP.CLIENTE (ID,CLIENTE_ID,CONTRASENIA,ESTADO,NOMBRE,GENERO,EDAD,IDENTIFICACION,DIRECCION,TELEFONO) values ('1','vepa','12345','A','VERO VELASCO','FEMENINO','34','1721739231','ALANGASI','0992060516');
Insert into CUENTAS_BP.CLIENTE (ID,CLIENTE_ID,CONTRASENIA,ESTADO,NOMBRE,GENERO,EDAD,IDENTIFICACION,DIRECCION,TELEFONO) values ('22','cliente','password','A','nombre apellido','masculino','10','77777','direccion','787878787');
Insert into CUENTAS_BP.CLIENTE (ID,CLIENTE_ID,CONTRASENIA,ESTADO,NOMBRE,GENERO,EDAD,IDENTIFICACION,DIRECCION,TELEFONO) values ('23','uououou','uououo','A','jljljl','ljljl','78','7979797797','ljljlj','9797979');
--------------------------------------------------------
--  DDL for Index CLIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CUENTAS_BP"."CLIENTE_PK" ON "CUENTAS_BP"."CLIENTE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "CUENTAS_BP"."CLIENTE" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "CUENTAS_BP"."CLIENTE" ADD CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CUENTAS_BP"."CLIENTE" MODIFY ("ID" NOT NULL ENABLE);
