--------------------------------------------------------
-- Archivo creado  - lunes-mayo-02-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CUENTA
--------------------------------------------------------

  CREATE TABLE "CUENTAS_BP"."CUENTA" 
   (	"ID" NUMBER, 
	"NUMERO_CUENTA" VARCHAR2(20 BYTE), 
	"TIPO_CUENTA" VARCHAR2(20 BYTE), 
	"SALDO_INICIAL" NUMBER, 
	"ESTADO" CHAR(1 BYTE), 
	"CODIGO_CLIENTE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CUENTAS_BP.CUENTA
SET DEFINE OFF;
Insert into CUENTAS_BP.CUENTA (ID,NUMERO_CUENTA,TIPO_CUENTA,SALDO_INICIAL,ESTADO,CODIGO_CLIENTE) values ('3','123456','AHORROS','15','A','1');
--------------------------------------------------------
--  DDL for Index CUENTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CUENTAS_BP"."CUENTA_PK" ON "CUENTAS_BP"."CUENTA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CUENTA
--------------------------------------------------------

  ALTER TABLE "CUENTAS_BP"."CUENTA" ADD CONSTRAINT "CUENTA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CUENTAS_BP"."CUENTA" MODIFY ("ID" NOT NULL ENABLE);
