--------------------------------------------------------
-- Archivo creado  - lunes-mayo-02-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MOVIMIENTO
--------------------------------------------------------

  CREATE TABLE "CUENTAS_BP"."MOVIMIENTO" 
   (	"ID" NUMBER, 
	"FECHA" DATE, 
	"TIPO_MOVIMIENTO" VARCHAR2(20 BYTE), 
	"VALOR" NUMBER, 
	"SALDO" NUMBER, 
	"CODIGO_CUENTA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CUENTAS_BP.MOVIMIENTO
SET DEFINE OFF;
Insert into CUENTAS_BP.MOVIMIENTO (ID,FECHA,TIPO_MOVIMIENTO,VALOR,SALDO,CODIGO_CUENTA) values ('13',to_date('02/05/2022','DD/MM/RRRR'),'1','2','14','3');
Insert into CUENTAS_BP.MOVIMIENTO (ID,FECHA,TIPO_MOVIMIENTO,VALOR,SALDO,CODIGO_CUENTA) values ('11',to_date('02/05/2022','DD/MM/RRRR'),'1','5','7','3');
Insert into CUENTAS_BP.MOVIMIENTO (ID,FECHA,TIPO_MOVIMIENTO,VALOR,SALDO,CODIGO_CUENTA) values ('12',to_date('02/05/2022','DD/MM/RRRR'),'1','5','12','3');
Insert into CUENTAS_BP.MOVIMIENTO (ID,FECHA,TIPO_MOVIMIENTO,VALOR,SALDO,CODIGO_CUENTA) values ('14',to_date('02/05/2022','DD/MM/RRRR'),'1','1','15','3');
Insert into CUENTAS_BP.MOVIMIENTO (ID,FECHA,TIPO_MOVIMIENTO,VALOR,SALDO,CODIGO_CUENTA) values ('15',to_date('02/05/2022','DD/MM/RRRR'),'1','10','25','3');
Insert into CUENTAS_BP.MOVIMIENTO (ID,FECHA,TIPO_MOVIMIENTO,VALOR,SALDO,CODIGO_CUENTA) values ('16',to_date('02/05/2022','DD/MM/RRRR'),'1','5','30','3');
Insert into CUENTAS_BP.MOVIMIENTO (ID,FECHA,TIPO_MOVIMIENTO,VALOR,SALDO,CODIGO_CUENTA) values ('17',to_date('02/05/2022','DD/MM/RRRR'),'0','15','15','3');
--------------------------------------------------------
--  DDL for Index MOVIMIENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CUENTAS_BP"."MOVIMIENTO_PK" ON "CUENTAS_BP"."MOVIMIENTO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MOVIMIENTO
--------------------------------------------------------

  ALTER TABLE "CUENTAS_BP"."MOVIMIENTO" ADD CONSTRAINT "MOVIMIENTO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CUENTAS_BP"."MOVIMIENTO" MODIFY ("ID" NOT NULL ENABLE);
